name: Discord Watch Together Reminder

on:
  schedule:
    - cron: '2 23 * * *'  # Runs every day at 8:02 JST (23:02 UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Run Discord reminder script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: node discord_watch_together_reminder.js 